# Generated by Django 5.2.8 on 2025-11-13 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photographer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photographer_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=500)),
            ],
            options={
                "verbose_name": "Photographer",
                "verbose_name_plural": "Photographers",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["photographer_id"],
                        name="photos_phot_photogr_6ceae3_idx",
                    ),
                    models.Index(fields=["name"], name="photos_phot_name_a10655_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_id", models.IntegerField(db_index=True, unique=True)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("url", models.URLField(max_length=500)),
                ("src_url", models.URLField(max_length=500)),
                ("avg_color", models.CharField(max_length=7)),
                ("alt", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="photos.photographer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="photos_phot_id_b5fb7e_idx"),
                    models.Index(
                        fields=["photographer"], name="photos_phot_photogr_9f9a21_idx"
                    ),
                ],
            },
        ),
    ]
