# Generated by Django 5.2.8 on 2025-11-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photographer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='alt',
            field=models.TextField(db_index=True),
        ),
    ]
